Setting.defaults['home_page.general.plugins'] = ['home_page']
Setting.defaults['home_page.general.navigation.items'] = ['pages', 'users', 'settings', 'authentication']
Setting.defaults['home_page.general.footer_navigation.items'] = []
Setting.defaults['home_page.general.available_apis'] = ['volontariat']
Setting.defaults['home_page.general.enabled_apis'] = []
Setting.defaults['home_page.general.partial_paths'] = []
Setting.defaults['home_page.apis.providers.volontariat.hosts.development'] = 'http://localhost:3001'
Setting.defaults['home_page.apis.providers.volontariat.hosts.production'] = 'http://Volontari.at'
Setting.defaults['home_page.apis.providers.volontariat.user_id'] = 0