require 'v8'
require 'twitter-bootswatch-rails'
require 'coffee_script'
require 'momentjs-rails'
require 'bootstrap3-datetimepicker-rails'
require 'jquery-rails'
require 'jquery-ui-rails'
require 'devise'
require 'active_record'
require 'friendly_id'
require 'recaptcha/rails'
require 'protected_attributes'
require 'active_record/deprecated_finders'
require 'simple_form'
require 'simple-navigation'  
require 'simple-navigation-bootstrap'
require 'redcarpet'
require 'albino'
require 'nokogiri'
require 'auto_html'
require 'will_paginate'
require 'will_paginate-bootstrap'
require 'turbolinks'
require 'uglifier'
require 'yui/compressor'
require 'httparty'
require 'rails-settings-cached'
require 'liquid'
require 'selectize-rails'
require 'acts_as_list'

require 'home_page/api_provider_host'
require 'home_page/navigation'
require 'home_page/pagination_metadata'
require 'home_page/simple_navigation_renderer/breadcrumbs_without_method_links'
require 'home_page/simple_navigation_renderer/twitter_sidenav'

require 'home_page/engine'

module HomePage
end
